### ISSUE TITLE
OpenCV 3 not supported

### ISSUE THREAD

**Issue by AIBluefisher** [hlzz/libvot#19]
In your code, you use the nonfree module of OpenCV 2, thus when build your code the OpenCV 3 cannot be used. Hope write this down in your installation guide.

**Comment by hlzz** [comment]
@AIBluefisher The non-free module is used for feature extraction (sift) and can be removed. OpenCV 3 can also be built with non-free modules (opencv_contrib). But I am not sure the currently repo can work with opencv3 due to the interface changes. You can go ahead and try, and pull request your findings if necessary :).
