### ISSUE TITLE
Would you provide the script of openMVG's SIFT extraction?

### ISSUE THREAD

**Issue by willard-yuan** [hlzz/libvot#4]
@hlzz It's very interesting of the project. Would you provide the script of openMVG's SIFT extraction, i.e. the script to use openMVG's SIFT function and save it to a file with suffix '.desc' like the data in `test_data`?

**Comment by hlzz** [comment]
Thanks for your interests. If you successfully compile openMVG, you will find a executable called openMVG_main_ComputeFeatures. But that may be cumbersome for you because you may not want to build openMVG in the first place. The openmvg support is to facilitate the openmvg users. I plan to add some more feature support and even maybe a self-contained feature detector. So stay tuned!

**Comment by a-vlad** [comment]
Also maybe add support to build from cm:Mat features. Rather then bin file . Also would the exosting implementation work with 128 sized KAZE vector rather then sift features?

**Comment by willard-yuan** [comment]
@hlzz I have written a C++ SIFT API with VLFeat. I'll try the openMVG_main_ComputeFeatures and I'll pull request after I know the data storage format of  '.desc'

**Comment by willard-yuan** [comment]
I see OpenMVG is [added a SIFT implementation](https://github.com/openMVG/openMVG/issues/556) and the performace is comparable to VLFEAT SIFT. The SIFT implementation can be split from the OpenMVG and we can add them to the libvot.

**Comment by hlzz** [comment]
@willard-yuan Actually you can extract sift using VLFeat and convert it to the format of libvot: https://github.com/hlzz/libvot/blob/master/src/utils/data_types.h here. I am not sure if we can naively extract openmvg sift code and dump it into libvot, since we use BSD license and they use LGPL, which is contagious. Anyway, thanks for your contribution and look forward to your PR!

**Comment by hlzz** [comment]
@a-vlad Thanks for you interests. We have plans to support more types of features. Stay tuned.

**Comment by pmoulon** [comment]
FYI @hlzz OpenMVG code is under MPL2 (not contagious)

**Comment by hlzz** [comment]
libvot now has a feature detector in development, called libvot_feature in example. Feel free to try and test it. So this issue will be closed. ;)
