### ISSUE TITLE
Wrong result in web_search

### ISSUE THREAD

**Issue by ashkart** [hlzz/libvot#8]
Hello again!
I just tryed libvot examples on more bigger image collection. See what i get.
![default](https://cloud.githubusercontent.com/assets/13589687/16074545/9904491a-32f3-11e6-8315-4927ae920390.JPG)

Result isn't even close. But when i try to compare query image and "top ranked" image from result by native opencv functions (same libvot used, but without convertion to SiftData structure, just Flann computing of descriptors), i got false, and true with only same pictures. It looks like something went wrong ))))

**Comment by hlzz** [comment]
Can you share the dataset for me to test it? Also note that we now have a official [documentation](http://hlzz.github.io/libvot/doc/html/index.html) for your reference.

**Comment by ashkart** [comment]
Yeah, shared it on dropbox [https://www.dropbox.com/s/khvc1jibih1en5z/dataset.zip?dl=0](here)

**Comment by hlzz** [comment]
Thanks for this dataset. I have tested it on my machine. It does not performance very well for these unrealistic photos. One reason is that the vocabulary tree algorithm is just based on a bunch of salient features and doesn't go that far into the semantic meaning. It also shows that computer vision is far from mature and count on you to make it better :) If you are interested in the algorithm behind, you can check out http://www-inst.eecs.berkeley.edu/~cs294-6/fa06/papers/nister_stewenius_cvpr2006.pdf

**Comment by hlzz** [comment]
FYI, this is the query result of 254.jpg returned by google image:https://www.google.com/search?newwindow=1&hl=en&tbs=simg:CAESzgEJLmCfkwhyEUgawgELELCMpwgaYgpgCAMSKNsL1gv9FdcV_1BXcC_1gLwwuNHvMU0ijGItMowyL6KtkhpyqtKtgh0CEaMI9dT0mkWBxn1ipBUCkNjQLUfeiUyY7NCvUwBYDzGCO5FIMud3ifFEu_12UxYSNR_1niADDAsQjq7-CBoKCggIARIENNoNJgwLEJ3twQkaOwoICgZuYXR1cmUKCAoGZ2FyZGVuCggKBmZsb3dlcgoSChBib3RhbmljYWwgZ2FyZGVuCgcKBXBsYW50DA&q=egidio+antonaccio+paintings&tbm=isch&sa=X&ved=0ahUKEwiqr-Xok6rNAhXDJZQKHVY_Ai4Qsw4ILw&biw=1440&bih=812&dpr=2
As you can see, the query result is acceptable since the images you give me are already in a very similar style. It just cannot differentiate the fine nuances. It is sort of related to how you define similarity.

**Comment by ashkart** [comment]
So the parameters of vocab tree builder are the point.

**Comment by ashkart** [comment]
Yeah. I just make sure about opencv tools natively doesnt care about pictures'es semantic. Look at this screen: its almost 100% precise recognizing (all non-254.jpg pictures have 0 matches, except 2 or 3 pics wich have 1-3 matches). 
![default](https://cloud.githubusercontent.com/assets/13589687/16086966/fe1a3b62-3329-11e6-938f-4f6f69af22d1.JPG)
